site_name: KAIST Visual AI Group

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  font: false
  primary: custom
  icon:
    logo: material/safety-goggles
  favicon: material/safety-goggles

extra:
  analytics:
    provider: google
    property: G-823443TVP0

extra_css:
  - stylesheets/extra.css

markdown_extensions: 
  - attr_list
  - md_in_html
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

nav:
  - Home: index.md
  - People: people.md
  - Publications: publications.md
  - Courses: courses.md
  - News: news.md
  - Contact: contact.md
  - Internship: internship.md

plugins:
    - search
    - macros:
        include_yaml:
          - people: data/people.yml
          - publications: data/publications.yml
          - courses: data/courses.yml
          - research_highlights: data/research_highlights.yml
          - news: data/news.yml

copyright: Copyright &copy; 2021 - 2024 KAIST Visual AI Group
