site_name: KAIST Visual AI Group

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  font: false
  primary: custom

extra_css:
  - stylesheets/extra.css

markdown_extensions: 
  - attr_list
  - md_in_html
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

nav:
  - Home: index.md
  - People: people.md
  - Publications: publications.md
  - Courses: courses.md
  - News: news.md
  - Contact: contact.md

plugins:
    - search
    - macros:
        include_yaml:
          - people: data/people.yml
          - publications: data/publications.yml
          - courses: data/courses.yml
          - research_highlights: data/research_highlights.yml
          - news: data/news.yml

copyright: Copyright &copy; 2024 KAIST Visual AI Group
