site_name: KAIST Geometric AI Group
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  font: false
  primary: custom

extra_css:
  - stylesheets/extra.css

markdown_extensions: 
  - attr_list
  - md_in_html
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - People: people.md
  - Publications: publications.md

plugins:
    - search
    - macros

copyright: Copyright &copy; 2024 KAIST Geometric AI Group
